import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const routes = [
    { name: "Home", path: "/" },
    { name: "About", path: "/about" },
    { name: "Blogs", path: "/blogs" },
  ];

  return (
    <html className="p-5" lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex divide-x gap-1">
            {routes.map((route, index) => (
              <li className={index !== 0 ? "pl-1" : ""} key={index}>
                <Link href={route.path}>{route.name}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
